name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: actions/checkout@v2

    - name: Setup Prerequisites
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libsecret-1-dev

    - name: Prepare Keytar (Unix)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        chmod -R 777 ./
        .github/scripts/setup-keytar

    - name: Prepare Keytar (Windows)
      if: matrix.os == 'windows-latest'
      run: .github/scripts/setup-keytar.ps1

    - uses: actions/checkout@v2
    - name: Test commands
      run: make test-commands
