name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - uses: actions/checkout@v2
    - name: Test commands
      run: sh ./test/commands.sh
