name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        # Issue from X11, https://github.com/atom/node-keytar/issues/224
        #- ubuntu-latest
        - macos-latest
        - windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare Keytar (Unix)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        chmod -R 777 ./
        .github/scripts/setup-keytar

    - name: Prepare Keytar (Windows)
      if: matrix.os == 'windows-latest'
      run: .github/scripts/setup-keytar.ps1

    - uses: actions/checkout@v4
    - name: Test commands
      run: make test-commands
